function phi = phiFunc(xt, t, beta, omega)

phi = 0.5*erfc(xt/(2*sqrt(t))) + 0.5*exp(-omega*xt + omega^2 * t)*erfc(xt/(2*sqrt(t)) -omega*sqrt(t))...
    -0.5*exp(-beta*xt+(beta^2) *t)*erfc(xt/(2*sqrt(t)) - beta*sqrt(t))...
    -0.5*exp(-(omega-beta)*xt + (omega-beta)^2 * t) * erfc(xt/(2*sqrt(t)) - (omega-beta) * sqrt(t))...
    +exp((beta-omega)*xt + (beta-omega)^2 * t);